import StarHeader from "@/components/StarHeader";
import Project from "@/components/Project";

interface ProjectData {
  title: string;
  subTitle: string;
  skillsUsed: string;
  description: string[];
  image: string;
  githubLink: string;
  siteLink?: string;
}

const proffesionalProjects: ProjectData[] = [
  {
    title: "LLAMA CHAT",
    subTitle: "Website",
    skillsUsed:
      "React, NextJS, tRPC, Pusher, Websockets, tailwindCSS, Typescript",
    description: [
      "A chat app built on top of websocket technology",
      "Mimics Discord or Microsoft Teams in functionality",
      "Has rudimentary user authentication that can be expanded upon",
      "Messages are encrypted and no session is stored once all parties leave the chat",
    ],
    image: "/llamachat.webp",
    githubLink: "https://github.com/JPTomorrow/nextjs-pusher-railway-chat-app",
    siteLink: "https://justins-chat-app.up.railway.app/",
  },
  {
    title: "Bill of Materials Generator",
    subTitle: "WPF Application",
    skillsUsed: "C#, WPF",
    description: [
      "Uses Revit API for interoperability with Autodesk Revit",
      "Generates Bill of Materials from the 3D CAD models that Revit produces",
      "Systems for calculating wire and Hanger systems for MEP conduit racks",
    ],
    image: "/bom-generator.webp",
    githubLink:
      "https://github.com/JPTomorrow/revit-bill-of-materials-generator",
  },
  {
    title: "WHATS A PNG",
    subTitle: "PNG Rust Library",
    skillsUsed:
      "Rust, Bit Manipulation, Implimentation of the PNG Specification",
    description: [
      "Implements the PNG specification in Rust per http://www.libpng.org/pub/png/spec/1.2/PNG-Contents.html",
      "Reads bytes of a .png file to create structured data out of it for use in other programs",
    ],
    image: "",
    githubLink: "https://github.com/JPTomorrow/whats-a-png",
    siteLink: "https://crates.io/crates/whats-a-png",
  },
  {
    title: "JSON | TOML | YAML converter",
    subTitle: "Website",
    skillsUsed:
      "Rust, Tauri, tsu (Rust crate), tailwindCSS, NextJS, Typescript",
    description: [
      "Takes as input a JSON, Toml, or Yaml file and converts it to the other two formats",
      "Uses Rust to bring memory safety to file IO operations on the backend",
    ],
    image: "/converter.webp",
    githubLink: "https://github.com/JPTomorrow/json-toml-yaml-converter",
    siteLink: "https://github.com/JPTomorrow/json-toml-yaml-converter/releases",
  },
  {
    title: "Game of Life",
    subTitle: "Website",
    skillsUsed: "React, NextJS, three.js, WebGL",
    description: [
      "A classic implementation of Conway's Game of Life",
      "Built using 3D web technologies like three.js",
    ],
    image: "/gol.webp",
    githubLink: "https://github.com/JPTomorrow/nextjs-gol",
    siteLink: "https://nextjs-game-of-life-production.up.railway.app/",
  },
  {
    title: "Marathon Training Videos",
    subTitle: "Website",
    skillsUsed: "Vue, Microsoft Azure, API's",
    description: [
      "A website for training marathon field workers in construction safety",
      "The employees must watch a video and complete a test",
      "The results of that test will be emailed to their supervisor for review",
      "Uses Microsoft azure to host the website and Azure functions to send the email to a supervisor",
    ],
    image: "/marathon-training-videos-pic.webp",
    githubLink: "https://github.com/JPTomorrow/marathon-training-videos",
  },
  {
    title: "Bluebeam In Wall / Fire Alarm BOM Generator",
    subTitle: "CLI Application",
    skillsUsed: "C#, .NET Core, PDF format parsing",
    description: [
      "Generates a Bill of Materials for In Wall devices and Fire Alarm Systems using PDF's generated by Bluebeam",
      "Bluebeam has a system for custom markups that is used to build the in wall device boxes",
      "Uses Microsoft azure to host the website and Azure functions to send the email to a supervisor",
    ],
    image: "/bluebeam-in-wall-fire-alarm.webp",
    githubLink: "https://github.com/JPTomorrow/bluebeam-pthree-in-wall",
  },
];

const Projects = () => {
  return (
    <>
      <StarHeader className="std-hdr-t-pad">Professional Projects</StarHeader>
      <div className="grid grid-cols-2 gap-5 mx-[50px] p-5 mt-[75px] mb-[100px]">
        {Object.values(proffesionalProjects).map((project, i: number) => (
          <Project
            key={i}
            title={project["title"]}
            subTitle={project["subTitle"]}
            skillsUsed={project["skillsUsed"]}
            description={project["description"]}
            image={project["image"]}
            githubLink={project["githubLink"]}
            siteLink={project["siteLink"]}
          />
        ))}
      </div>
    </>
  );
};

export default Projects;
